export interface ArticleDTO {
  slug: string;
  title: string;
  summary: string;
  content: string;
  coverImage?: string;
  category?: string;
  tags?: string[];
  source?: string;
  publishedAt: string;
}

export const FALLBACK_ARTICLES: ArticleDTO[] = [
  {
    slug: "strategia-dywidendowa-2025",
    title: "Strategia dywidendowa 2025: które spółki z GPW wyróżniają się stabilnością",
    summary: "Przegląd spółek z GPW o przewidywalnych wypłatach i rosnących stopach dywidendy. Analizujemy sektory, payout ratio i ryzyko.",
    content: "W 2025 roku inwestorzy dywidendowi skupiają się na spółkach o stabilnych przepływach pieniężnych i konserwatywnym zadłużeniu. Wśród kandydatów znajdują się banki z wysokimi współczynnikami kapitałowymi, spółki energetyczne z rosnącym udziałem OZE oraz wybrane firmy z sektora paliwowego i surowcowego. Kluczowe wskaźniki: payout ratio poniżej 70%, dług netto/EBITDA poniżej 2x, stabilny FCF. Warto również monitorować politykę dywidendową spółek – szczególnie tam, gdzie zarząd deklaruje kontynuację wypłat lub wzrost dywidendy w najbliższych latach.",
    coverImage: "https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=1200&q=90",
    category: "gielda",
    tags: ["dywidendy", "gpw", "strategie"],
    source: "FusionFinance.pl",
    publishedAt: new Date().toISOString(),
  },
  {
    slug: "budzet-domowy-2025",
    title: "Jak ułożyć budżet domowy w 2025? 5 kroków Money.pl",
    summary: "Proste zasady 50/30/20, poduszka bezpieczeństwa i automatyzacja oszczędzania.",
    content: "Model 50/30/20 to dobry start: 50% na potrzeby, 30% na przyjemności, 20% na oszczędności/inwestycje. Ustaw przelewy stałe na konto oszczędnościowe, monitoruj subskrypcje, negocjuj rachunki. Poduszka 3–6 miesięcy wydatków daje spokój przy zmianie pracy.",
    coverImage: "https://images.unsplash.com/photo-1454165205744-3b78555e5572?w=1200&q=90",
    category: "finanse",
    tags: ["budżet", "oszczędzanie", "finanse osobiste", "polska"],
    source: "Money.pl / oprac. FusionFinance",
    publishedAt: new Date(Date.now() - 26 * 3600_000).toISOString(),
  },
  {
    slug: "kredyt-vs-gotowka",
    title: "Kupić na kredyt czy za gotówkę? Bankier.pl porównuje koszty",
    summary: "RRSO, prowizje i ubezpieczenia potrafią podbić cenę finansowania – kiedy kredyt ma sens?",
    content: "Przy wyborze kredytu liczy się pełne RRSO, prowizja i cross-sell. Jeśli masz poduszkę i brak alternatywnych inwestycji, kredyt może być droższy niż wypłata gotówki. Zawsze porównaj oferty w porównywarce, negocjuj marżę i unikaj zbędnych ubezpieczeń.",
    coverImage: "https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=1200&q=90",
    category: "finanse",
    tags: ["kredyt", "rrso", "porownywarka", "polska"],
    source: "Bankier.pl / oprac. FusionFinance",
    publishedAt: new Date(Date.now() - 27 * 3600_000).toISOString(),
  },
  {
    slug: "biznes-pln-umacnia",
    title: "Biznes: PLN mocny, eksporterzy zmieniają strategię cenową",
    summary: "Umocnienie złotego do EUR i USD wymusza renegocjacje cenników i zabezpieczenia kursowe.",
    content: "Silny PLN obniża przychody w złotych. Eksporterzy: aktualizacja cenników co kwartał, hedging forward na 3–6 miesięcy, dywersyfikacja walutowa faktur. Ważne: koszty surowców i transportu w USD mogą neutralizować część ryzyka.",
    coverImage: "https://images.unsplash.com/photo-1553729459-efe14ef6055d?w=1200&q=90",
    category: "biznes",
    tags: ["eksport", "pln", "hedging", "polska"],
    source: "FusionFinance.pl",
    publishedAt: new Date(Date.now() - 28 * 3600_000).toISOString(),
  },
  {
    slug: "pit-2025-ulgi",
    title: "PIT 2025: ulgi i odliczenia, o których łatwo zapomnieć",
    summary: "Ulga na internet, IKZE, darowizny, termomodernizacja – przypomnienie przed rozliczeniem.",
    content: "Przed złożeniem PIT-37/PIT-36 sprawdź: darowizny na OPP, ulgę na internet (do 760 zł), IKZE (odliczenie wpłat), termomodernizację (do 53 tys. zł), ulgę rehabilitacyjną, ulgę na dzieci. Korzystaj z e-PIT i miej dowody wpłat.",
    coverImage: "https://images.unsplash.com/photo-1450101499163-c8848c66ca85?w=1200&q=90",
    category: "finanse",
    tags: ["pit", "podatki", "ulgi", "polska"],
    source: "Money.pl / oprac. FusionFinance",
    publishedAt: new Date(Date.now() - 29 * 3600_000).toISOString(),
  },
  {
    slug: "notowania-gpw-otwarcie",
    title: "Notowania: WIG20 otwiera się wyżej, energia i banki prowadzą",
    summary: "Poranny przegląd sesji: które sektory ciągną indeksy i gdzie widać największe obroty.",
    content: "Na otwarciu WIG20 zyskuje dzięki energetyce i bankom, z lekkim obciążeniem ze strony górnictwa. Obroty skoncentrowane na PKO i PKN. W tle oczekiwania na dane CPI i decyzję EBC. Uwaga na wsparcia Fibo i poziomy L2.",
    coverImage: "https://images.unsplash.com/photo-1535320903710-d993d3d77d29?w=1200&q=90",
    category: "gielda",
    tags: ["wig20", "sesja", "obroty", "polska"],
    source: "Parkiet / oprac. FusionFinance",
    publishedAt: new Date(Date.now() - 30 * 3600_000).toISOString(),
  },
  {
    slug: "porownywarki-konta",
    title: "Porównywarka: konto osobiste 2025 – gdzie najniższe opłaty?",
    summary: "Ranking rachunków osobistych: opłaty za kartę, bankomaty, przelewy natychmiastowe.",
    content: "Przy wyborze ROR sprawdź: opłata za kartę i warunki zwolnienia (obrót, wpływ), darmowe wypłaty z bankomatów w PL/UE, przelewy natychmiastowe i BLIK, kantory online wbudowane. Dla oszczędności: konta z promocyjnym oprocentowaniem, ale z limitem kwoty.",
    coverImage: "https://images.unsplash.com/photo-1545239351-1141bd82e8a6?w=1200&q=90",
    category: "finanse",
    tags: ["konto", "bank", "porownywarka", "polska"],
    source: "FusionFinance.pl",
    publishedAt: new Date(Date.now() - 31 * 3600_000).toISOString(),
  },
  {
    slug: "global-makro-energia",
    title: "Świat: ceny energii i geopolityka – co napędza rynki surowców?",
    summary: "Rosną napięcia na Bliskim Wschodzie, a magazyny gazu w UE pełne. Jak to wpływa na Brent i TTF?",
    content: "Ceny Brent reagują na ryzyko geopolityczne, ale wysoki poziom zapasów w UE chłodzi panikę. TTF spada dzięki ciepłej zimie i LNG z USA, ale ryzykiem są przerwy w dostawach z Norwegii. Inwestorzy obserwują indeks dolara i popyt z Chin.",
    coverImage: "https://images.unsplash.com/photo-1508387024700-9fe5c0b25c95?w=1200&q=90",
    category: "rynki",
    tags: ["energia", "ropa", "gaz", "swiat"],
    source: "Forsal / oprac. FusionFinance",
    publishedAt: new Date(Date.now() - 32 * 3600_000).toISOString(),
  },
  {
    slug: "global-indeksy-usa-azja",
    title: "Świat: USA rekordy, Azja mieszanina – przegląd indeksów",
    summary: "S&P 500 blisko ATH, Nikkei zmienny przez BoJ, Europa w trendzie bocznym.",
    content: "USA korzystają z siły big tech i stabilnych wyników. Azja pod presją umacniającego się jena i danych z Chin. Europa w konsolidacji, czeka na ruch EBC. Uwaga na rotację sektorową i korelację z rentownościami 10Y UST.",
    coverImage: "https://images.unsplash.com/photo-1611078489935-0cb964de46d6?w=1200&q=90",
    category: "rynki",
    tags: ["usa", "azja", "indeksy", "swiat"],
    source: "Reuters / oprac. FusionFinance",
    publishedAt: new Date(Date.now() - 33 * 3600_000).toISOString(),
  },
  {
    slug: "fx-hedging-eksporterow",
    title: "Jak eksporterzy mogą tanio zabezpieczyć ryzyko walutowe w 2025?",
    summary: "Praktyczny przewodnik po strategiach hedgingowych dla eksporterów: forward, opcje zero-cost collar, natural hedging.",
    content: "Zmienność złotego w relacji do EUR i USD ponownie rośnie wraz z cyklem stóp procentowych. Eksporterzy mogą ograniczyć ryzyko kursowe, wykorzystując kontrakty forward (krótkie terminy, precyzyjne dopasowanie wartości), strategie collar (opcje kupna/sprzedaży ograniczające koszt premii) oraz natural hedging (bilansowanie wpływów/wywodów w tej samej walucie). Warto ocenić wpływ zabezpieczeń na marżę operacyjną, rotację kapitału obrotowego oraz wymogi księgowe (hedge accounting).",
    coverImage: "https://images.unsplash.com/photo-1454165205744-3b78555e5572?w=1200&q=90",
    category: "waluty",
    tags: ["forex", "hedging", "eksport"],
    source: "FusionFinance.pl",
    publishedAt: new Date(Date.now() - 3600_000).toISOString(),
  },
  {
    slug: "bitcoin-etf-spot-implikacje",
    title: "ETF-y spot na Bitcoina: implikacje dla płynności i zmienności rynku",
    summary: "Analizujemy, jak ETF-y spot mogą zmienić profile inwestorów na rynku kryptowalut i jakie ryzyka pozostają.",
    content: "Debiut ETF-ów spot na Bitcoina zwiększa dostępność aktywa dla inwestorów instytucjonalnych i detalicznych. Struktura funduszy opartych na fizycznym BTC wpływa na popyt i podaż, a także na mechanizmy arbitrażu pomiędzy ceną ETF a ceną spot. Zmienność może krótkoterminowo rosnąć, ale w dłuższym horyzoncie większa płynność i przejrzystość regulacyjna mogą stabilizować rynek. Ryzyka: koncentracja u depozytariuszy, kwestie bezpieczeństwa custody oraz wpływ na dominance BTC vs altcoiny.",
    coverImage: "https://images.unsplash.com/photo-1518546305927-5a555bb7020d?w=1200&q=90",
    category: "crypto",
    tags: ["bitcoin", "etf", "kryptowaluty"],
    source: "FusionFinance.pl",
    publishedAt: new Date(Date.now() - 2 * 3600_000).toISOString(),
  },
  {
    slug: "inflacja-2025-scenariusze",
    title: "Inflacja 2025: scenariusze bazowe i ryzyka dla stóp procentowych",
    summary: "Przegląd scenariuszy inflacyjnych dla Polski i strefy euro oraz ich wpływ na politykę banków centralnych.",
    content: "Bazowy scenariusz zakłada stopniowy spadek inflacji bazowej dzięki wygaszaniu efektów podażowych i słabszej dynamice płac realnych. Ryzyka w górę: ceny energii i żywności, napięcia geopolityczne. Ryzyka w dół: słabszy popyt zewnętrzny, mocniejszy złoty. Dla RPP oznacza to przestrzeń do ostrożnych obniżek dopiero po potwierdzeniu trendu dezinflacyjnego; dla EBC – utrzymanie restrykcji do czasu wyraźnego zejścia inflacji bazowej poniżej 3%.",
    coverImage: "https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?w=1200&q=90",
    category: "gospodarka",
    tags: ["inflacja", "stopy procentowe", "makro"],
    source: "FusionFinance.pl",
    publishedAt: new Date(Date.now() - 3 * 3600_000).toISOString(),
  },
  {
    slug: "portfel-60-40-w-ery-wysokich-stop",
    title: "Czy portfel 60/40 ma sens przy wyższych stopach procentowych?",
    summary: "Oceniamy rolę obligacji skarbowych w klasycznym portfelu 60/40 oraz alternatywy: TIPS, złoto, strategie absolutnej stopy zwrotu.",
    content: "Wyższe stopy procentowe zwiększają atrakcyjność obligacji skarbowych jako amortyzatora zmienności akcji. Jednak korelacje akcji/obligacji pozostają zmienne w krótkim terminie, zwłaszcza przy szokach inflacyjnych. Portfel 60/40 można wzbogacić o obligacje indeksowane inflacją (TIPS), krótkoterminowe papiery skarbowe, a także niewielką ekspozycję na złoto lub strategie absolute return. Kluczowe pozostaje rebalancing i kontrola ryzyka duration.",
    coverImage: "https://images.unsplash.com/photo-1526304640581-d334cdbbf45e?w=1200&q=90",
    category: "strategie",
    tags: ["portfel", "obligacje", "dywersyfikacja"],
    source: "FusionFinance.pl",
    publishedAt: new Date(Date.now() - 4 * 3600_000).toISOString(),
  },
  {
    slug: "rynki-usa-sezon-wynikow",
    title: "Wall Street wchodzi w sezon wyników: na co patrzeć w I kwartale?",
    summary: "S&P 500 blisko historycznych szczytów, ale spready kredytowe rosną. Sprawdzamy, które sektory mogą pozytywnie zaskoczyć.",
    content: "Analitycy prognozują jednocyfrowy wzrost EPS dla spółek z indeksu S&P 500. Największy potencjał niespodzianek widzimy w sektorach technologii chmurowej, półprzewodników oraz finansów, gdzie wyższe stopy procentowe wspierają marże odsetkowe. Ryzykiem pozostają marże w handlu detalicznym i presja płacowa w usługach. W krótkim terminie liczy się guidance zarządów oraz tempo buybacków.",
    coverImage: "https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=1200&q=90",
    category: "rynki",
    tags: ["usa", "wyniki", "akcje"],
    source: "Reuters / oprac. FusionFinance",
    publishedAt: new Date(Date.now() - 5 * 3600_000).toISOString(),
  },
  {
    slug: "rynki-azja-boj",
    title: "BoJ sygnalizuje koniec ujemnych stóp – co to znaczy dla Nikkei i jena?",
    summary: "Bank Japonii przygotowuje rynek na odejście od polityki YCC. Analizujemy wpływ na eksport, jena i kapitał zagraniczny.",
    content: "Potencjalne zakończenie kontroli krzywej dochodowości może umocnić jena i ochłodzić entuzjazm wokół rekordowych poziomów Nikkei 225. Spółki eksportowe mogą odczuć presję marż, a inwestorzy zagraniczni – wzrost kosztu zabezpieczenia walutowego. Jednocześnie wyższe rentowności JGB mogą przyciągnąć kapitał z rynku obligacji USA i Europy.",
    coverImage: "https://images.unsplash.com/photo-1445633742902-5e4e1f0b3c89?w=1200&q=90",
    category: "rynki",
    tags: ["azja", "boj", "obligacje"],
    source: "Bloomberg / oprac. FusionFinance",
    publishedAt: new Date(Date.now() - 6 * 3600_000).toISOString(),
  },
  {
    slug: "rynki-europa-stoxx600",
    title: "Europa: defensywa czy wzrost? SToxx 600 balansuje między value a growth",
    summary: "Sektor finansowy korzysta ze stóp, ale przemysł cierpi na słabszym popycie. Gdzie szukać alfa na europejskich parkietach?",
    content: "W otoczeniu słabszego przemysłu niemieckiego atrakcyjnie wyglądają spółki z sektora obronnego, cyberbezpieczeństwa oraz wybrane utility z ekspozycją na OZE. Rotacja value/growth w Europie pozostaje wrażliwa na ruchy EUR/USD i poziom realnych stóp. Dywidendy i buybacki stają się kluczowym elementem całkowitej stopy zwrotu.",
    coverImage: "https://images.unsplash.com/photo-1450101499163-c8848c66ca85?w=1200&q=90",
    category: "rynki",
    tags: ["europa", "akcje", "strategie"],
    source: "FusionFinance.pl",
    publishedAt: new Date(Date.now() - 7 * 3600_000).toISOString(),
  },
  {
    slug: "gielda-top-exchanges",
    title: "20 największych giełd świata: wolumen, godziny handlu i liderzy sektorów",
    summary: "Przegląd parkietów od NYSE i NASDAQ po LSE, TSE, HKEX i B3. Dane o wolumenach oraz dominujących sektorach.",
    content: "Globalne rynki akcji różnią się strukturą sektorową i płynnością. NYSE/NASDAQ dominują w technologiach i finansach, LSE w surowcach i finansach, TSE w przemyśle i motoryzacji, HKEX w finansach i nieruchomościach, a B3 w surowcach i bankach. Inwestorzy globalni powinni uwzględniać strefy czasowe, koszty transakcyjne, podatki u źródła oraz dostęp do danych rynkowych w czasie rzeczywistym.",
    coverImage: "https://images.unsplash.com/photo-1430163393927-3dab9af7ea38?w=1200&q=90",
    category: "gielda",
    tags: ["giełdy", "dane", "global"],
    source: "FusionFinance.pl",
    publishedAt: new Date(Date.now() - 8 * 3600_000).toISOString(),
  },
  {
    slug: "gielda-wykresy-lcp",
    title: "Jak czytać wolumen i LOB? Praktyczny przewodnik po głębokości rynku",
    summary: "Depth of Market, poziomy bid/ask i śledzenie przepływów zleceń pomagają identyfikować wsparcia i opory intraday.",
    content: "Order book ujawnia, gdzie rynek absorbuje lub odrzuca podaż/popyt. Kluczowe metryki: delta wolumenu, imbalans między bid/ask, czas utrzymania poziomów oraz reakcje na wybicia. Narzędzia: heatmapy L2, footprinty, VWAP, poziomy likwidacji. Stosując je, należy pamiętać o płynności instrumentu i godzinach sesji.",
    coverImage: "https://images.unsplash.com/photo-1461749280684-dccba630e2f6?w=1200&q=90",
    category: "gielda",
    tags: ["wolumen", "order-book", "intraday"],
    source: "FusionFinance.pl",
    publishedAt: new Date(Date.now() - 9 * 3600_000).toISOString(),
  },
  {
    slug: "crypto-defi-2025",
    title: "DeFi 2025: realne przychody protokołów a ryzyko smart kontraktów",
    summary: "Które protokoły generują prawdziwy cash-flow z opłat, a które opierają się wyłącznie na emisji tokenów?",
    content: "Segment DEX-ów i pożyczek on-chain wraca do wzrostu wraz z aktywnością na L2. Kluczowe jest odróżnienie przychodów protokołu od inflacji tokena. Weryfikujemy audyty smart kontraktów, dywersyfikację źródeł przychodu, ryzyko koncentracji wśród validatorów oraz ekspozycję na stablecoiny algorytmiczne.",
    coverImage: "https://images.unsplash.com/photo-1518546305927-5a555bb7020d?w=1200&q=90",
    category: "crypto",
    tags: ["defi", "ethereum", "l2"],
    source: "FusionFinance.pl",
    publishedAt: new Date(Date.now() - 10 * 3600_000).toISOString(),
  },
  {
    slug: "crypto-halving-2024",
    title: "Halving Bitcoina: scenariusze podaży i zachowania górników",
    summary: "Analizujemy wpływ halvingu na hash rate, koszty energii i presję sprzedażową kopalni.",
    content: "Po halvingu marże górników zależą od ceny BTC, kosztów energii i efektywności sprzętu. Możliwe jest przejście części hash rate'u na tańsze regiony lub migracja do pooli oferujących udział w MEV. Historycznie halving zwiększał zmienność, ale korelacja z makro pozostaje istotna.",
    coverImage: "https://images.unsplash.com/photo-1611078489935-0cb964de46d6?w=1200&q=90",
    category: "crypto",
    tags: ["bitcoin", "halving", "górnicy"],
    source: "FusionFinance.pl",
    publishedAt: new Date(Date.now() - 11 * 3600_000).toISOString(),
  },
  {
    slug: "waluty-pln-perspektywy",
    title: "PLN w 2025: różnica stóp procentowych i napływ kapitału portfelowego",
    summary: "Złoty korzysta z wyższej realnej stopy procentowej i napływu środków z UE. Jak długo potrwa umocnienie?",
    content: "Model carry-trade dla PLN pozostaje atrakcyjny przy stabilnym otoczeniu globalnym. Ryzykiem jest pogorszenie sentymentu do rynków wschodzących i spadek eksportu do strefy euro. Inwestorzy powinni obserwować relację FRA/OIS, zmienność implikowaną na opcjach FX i decyzje RPP.",
    coverImage: "https://images.unsplash.com/photo-1507679622673-989605832e3d?w=1200&q=90",
    category: "waluty",
    tags: ["pln", "fx", "carry"],
    source: "NBP / FusionFinance",
    publishedAt: new Date(Date.now() - 12 * 3600_000).toISOString(),
  },
  {
    slug: "waluty-usd-eur",
    title: "EUR/USD: kiedy Fed i EBC zaczną ciąć stopy? Scenariusze dla pary głównej",
    summary: "Wycena ścieżki stóp w kontraktach OIS sugeruje pierwsze obniżki Fed w III kw. 2025. Co to znaczy dla EUR/USD?",
    content: "Przy realnych stopach powyżej 2% dolar pozostaje wspierany. Jeśli EBC zacznie luzować wcześniej, różnica rentowności może windować USD. W scenariuszu miękkiego lądowania USA spodziewamy się konsolidacji 1,06–1,12. Ryzyka: szoki geopolityczne, ceny energii oraz zmienność na rynku długu.",
    coverImage: "https://images.unsplash.com/photo-1489389944381-3471b5b30f04?w=1200&q=90",
    category: "waluty",
    tags: ["eurusd", "stopy", "fed"],
    source: "FusionFinance.pl",
    publishedAt: new Date(Date.now() - 13 * 3600_000).toISOString(),
  },
  {
    slug: "analiza-zlotowka-technicznie",
    title: "Złotówka w układzie harmonicznym: sekwencja Fibonacciego na EUR/PLN",
    summary: "Wykorzystujemy zniesienia Fibo do wyznaczenia stref wsparcia/oporu i oceniamy konfluencję z poziomami opcyjnymi.",
    content: "Zniesienia 38,2% oraz 61,8% na EUR/PLN zbiegają się z barierami opcyjnymi i dużymi wygasaniami. Dodanie wskaźników RSI/MACD pokazuje dywergencję spadkową. Scenariusz bazowy: konsolidacja 4,25–4,35, z ryzykiem wybicia przy wzroście zmienności implikowanej.",
    coverImage: "https://images.unsplash.com/photo-1520607162513-77705c0f0d4a?w=1200&q=90",
    category: "analizy",
    tags: ["fibo", "techniczna", "fx"],
    source: "FusionFinance.pl",
    publishedAt: new Date(Date.now() - 14 * 3600_000).toISOString(),
  },
  {
    slug: "analiza-wig20-fundy",
    title: "WIG20: momentum słabnie, ale wyceny wciąż atrakcyjne vs region",
    summary: "Łączymy wskaźniki fundamentalne (P/E, P/BV) z momentum cenowym, aby ocenić potencjał polskich blue chipów.",
    content: "Średnie P/E dla WIG20 pozostaje poniżej mediany rynków rozwiniętych, a ROE rośnie dzięki wyższym stopom i poprawie marż banków. Z drugiej strony momentum cenowe wyhamowuje, a wybór sektorów staje się kluczowy. Banki, energetyka z OZE i wybrane spółki przemysłowe wyglądają najciekawiej.",
    coverImage: "https://images.unsplash.com/photo-1545239351-1141bd82e8a6?w=1200&q=90",
    category: "analizy",
    tags: ["wig20", "fundamentalna", "momentum"],
    source: "FusionFinance.pl",
    publishedAt: new Date(Date.now() - 15 * 3600_000).toISOString(),
  },
  {
    slug: "rynki-usa-earnings-banks",
    title: "Banki z Wall Street otwierają sezon wyników – czego spodziewają się analitycy",
    summary: "Wyższe stopy wspierają marże, ale rosną koszty finansowania depozytów. Przegląd oczekiwań dla dużych banków USA.",
    content: "JPM, BAC i C wchodzą w sezon wyników z oczekiwaniami wzrostu NII, ale przy wyższych kosztach depozytów i normalizacji opłat inwestycyjnych. Rezerwy kredytowe mogą wzrosnąć w segmencie kart. Inwestorzy patrzą na wskazówki dot. buybacków i dynamiki kredytów korporacyjnych.",
    coverImage: "https://images.unsplash.com/photo-1526304640581-d334cdbbf45e?w=1200&q=90",
    category: "rynki",
    tags: ["usa", "banki", "wyniki"],
    source: "Reuters / oprac. FusionFinance",
    publishedAt: new Date(Date.now() - 16 * 3600_000).toISOString(),
  },
  {
    slug: "gielda-top20-wykresy",
    title: "20 największych giełd – które sektory dominują w 2025?",
    summary: "Mapa sektorowa od NYSE i NASDAQ po LSE, TSE, HKEX i B3. Technologia, finanse czy surowce?",
    content: "Technologia i finanse dominują na parkietach USA, sektor surowcowy i finansowy w Londynie, przemysł w Tokio, finanse i nieruchomości w Hongkongu, a surowce w São Paulo. Dywersyfikacja sektorowa pomaga balansować portfele globalne; warto uwzględnić strefy czasowe, podatki i koszty hedgingu walutowego.",
    coverImage: "https://images.unsplash.com/photo-1535320903710-d993d3d77d29?w=1200&q=90",
    category: "gielda",
    tags: ["giełdy", "sektory", "global"],
    source: "FusionFinance.pl",
    publishedAt: new Date(Date.now() - 17 * 3600_000).toISOString(),
  },
  {
    slug: "crypto-eth-staking-yields",
    title: "ETH staking: realne dochody po spadku opłat – co dalej z LST?",
    summary: "Analiza zwrotów ze stakingu po przejściu na PoS i spadku opłat transakcyjnych. Lido, Rocket Pool i alternatywy.",
    content: "Realne real-yield na ETH składają się z nagród za walidację i opłat. Spadek aktywności on-chain obniżył APR, ale MEV i wprowadzenie EIP-4844 mogą zwiększyć przychody. Ważne są ryzyka: koncentracja dostawców LST, smart contract risk i płynność tokenów pochodnych.",
    coverImage: "https://images.unsplash.com/photo-1611078489935-0cb964de46d6?w=1200&q=90",
    category: "crypto",
    tags: ["ethereum", "staking", "lst"],
    source: "FusionFinance.pl",
    publishedAt: new Date(Date.now() - 18 * 3600_000).toISOString(),
  },
  {
    slug: "waluty-try-em-fx",
    title: "Carry trade na rynkach wschodzących: które waluty wyglądają najlepiej?",
    summary: "Porównujemy realne stopy procentowe i zmienność na PLN, MXN, BRL, TRY. Gdzie carry jest najlepiej wynagradzane?",
    content: "Przy wysokich realnych stopach MXN i BRL pozostają atrakcyjne, PLN korzysta z relatywnie stabilnego otoczenia i napływu kapitału UE, a TRY pozostaje ryzykowna ze względu na inflację i politykę monetarną. Kluczowe: koszty hedgingu, płynność rynku opcji oraz korelacja z sentymentem EM.",
    coverImage: "https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?w=1200&q=90",
    category: "waluty",
    tags: ["carry trade", "em", "fx"],
    source: "FusionFinance.pl",
    publishedAt: new Date(Date.now() - 19 * 3600_000).toISOString(),
  },
  {
    slug: "analiza-makro-pmi",
    title: "PMI wraca nad 50? Jak odczyty wpływają na portfele akcyjne i FX",
    summary: "Scenariusze dla europejskich i amerykańskich indeksów oraz EUR/USD w zależności od poprawy wskaźników koniunktury.",
    content: "Poprawa PMI powyżej 50 wspiera sektor przemysłowy i cykliczne spółki, może też wzmacniać euro względem dolara przy rosnących oczekiwaniach inflacyjnych. Dla portfeli: zwiększenie ekspozycji na przemysł/OZE, monitorowanie spreadów kredytowych i kształtu krzywej rentowności.",
    coverImage: "https://images.unsplash.com/photo-1541354329998-f4d9a9f9297f?w=1200&q=90",
    category: "analizy",
    tags: ["pmi", "makro", "strategie"],
    source: "FusionFinance.pl",
    publishedAt: new Date(Date.now() - 20 * 3600_000).toISOString(),
  },
  {
    slug: "bankier-gpw-sentiment",
    title: "Bankier.pl: inwestorzy ostrożni przed sezonem wyników na GPW",
    summary: "Popyt na spółki defensywne rośnie, a obroty na NewConnect maleją. Bankier.pl wskazuje na rotację w kierunku dywidend.",
    content: "Raport Bankier.pl podkreśla wzrost zainteresowania spółkami dywidendowymi i sektorami defensywnymi. Mimo niskich obrotów na NC, blue chipy przyciągają kapitał ETF-ów. Monitoruj segment bankowy i energetyczny wraz z harmonogramem wypłat.",
    coverImage: "https://images.unsplash.com/photo-1590283603385-17ffb3a7f29f?w=1200&q=90",
    category: "gielda",
    tags: ["bankier", "gpw", "dywidendy"],
    source: "Bankier.pl",
    publishedAt: new Date(Date.now() - 21 * 3600_000).toISOString(),
  },
  {
    slug: "moneypl-inflacja-budzet",
    title: "Money.pl: inflacja wyhamowuje, ale budżet wciąż pod presją",
    summary: "Analiza wpływu niższej inflacji na dochody budżetowe i koszty obsługi długu. Co to znaczy dla złotego?",
    content: "Money.pl zwraca uwagę na spadek dynamiki CPI przy jednoczesnym wzroście kosztów finansowania długu. Umocnienie PLN możliwe, jeśli ścieżka inflacji spadnie poniżej 4%. Ryzyka: ceny energii, tempo wydatków publicznych, cykl stóp w USA.",
    coverImage: "https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?w=1200&q=90",
    category: "waluty",
    tags: ["inflacja", "budżet", "pln"],
    source: "Money.pl",
    publishedAt: new Date(Date.now() - 22 * 3600_000).toISOString(),
  },
  {
    slug: "independenttrader-zloto",
    title: "IndependentTrader: złoto vs. realne stopy – czy to moment na akumulację?",
    summary: "Porównanie złota do realnych stóp procentowych i dolara. Wnioski: okno akumulacji przy umiarkowanej inflacji.",
    content: "IndependentTrader podkreśla, że realne stopy wciąż są dodatnie, co hamuje rajd złota. Jednak spadek oczekiwań inflacyjnych i słabszy dolar mogą wywołać wybicie. Strategia: akumulacja w transzach, monitorowanie rentowności 10Y UST i DXY.",
    coverImage: "https://images.unsplash.com/photo-1610375461246-83df859d849d?w=1200&q=90",
    category: "rynki",
    tags: ["złoto", "stopy realne", "dxy"],
    source: "IndependentTrader.pl",
    publishedAt: new Date(Date.now() - 23 * 3600_000).toISOString(),
  },
  {
    slug: "egospodarka-eksport",
    title: "eGospodarka: eksport do strefy euro hamuje, firmy szukają rynków poza UE",
    summary: "Polskie firmy dywersyfikują sprzedaż poza UE w obliczu słabszego popytu w Niemczech i Francji.",
    content: "eGospodarka opisuje trend dywersyfikacji eksportu do USA i Azji. Kluczowe sektory: AGD, meble, automotive. Bariery: koszty frachtu, kursy walut, wymogi celne. PLN zyskuje, co obniża marże eksporterów – hedging walutowy wskazany.",
    coverImage: "https://images.unsplash.com/photo-1507679799987-c73779587ccf?w=1200&q=90",
    category: "rynki",
    tags: ["eksport", "pln", "handel"],
    source: "eGospodarka.pl",
    publishedAt: new Date(Date.now() - 24 * 3600_000).toISOString(),
  },
  {
    slug: "obserwatorfinansowy-makro",
    title: "Obserwator Finansowy: scenariusze miękkiego lądowania dla Polski",
    summary: "NBP może zaczekać z obniżkami, jeśli inflacja bazowa nie spadnie poniżej 4%. Prognozy PKB 2025 rosną.",
    content: "Obserwator Finansowy wskazuje, że spowolnienie kredytu i ostrożność konsumentów łagodzą presję cenową. Przy solidnym eksporcie usług cyfrowych PKB może rosnąć powyżej 2,5%. Ryzyka: energia, geopolityka, słabszy przemysł w Niemczech.",
    coverImage: "https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?w=1200&q=90",
    category: "analizy",
    tags: ["makro", "nbp", "pkb"],
    source: "ObserwatorFinansowy.pl",
    publishedAt: new Date(Date.now() - 25 * 3600_000).toISOString(),
  },
  {
    slug: "budzet-domowy-2025",
    title: "Jak ułożyć budżet domowy w 2025? 5 kroków Money.pl",
    summary: "Proste zasady 50/30/20, poduszka bezpieczeństwa i automatyzacja oszczędzania.",
    content: "Model 50/30/20 to dobry start: 50% na potrzeby, 30% na przyjemności, 20% na oszczędności/inwestycje. Ustaw przelewy stałe na konto oszczędnościowe, monitoruj subskrypcje, negocjuj rachunki. Poduszka 3–6 miesięcy wydatków daje spokój przy zmianie pracy.",
    coverImage: "https://images.unsplash.com/photo-1454165205744-3b78555e5572?w=1200&q=90",
    category: "finanse",
    tags: ["budżet", "oszczędzanie", "finanse osobiste"],
    source: "Money.pl / oprac. FusionFinance",
    publishedAt: new Date(Date.now() - 26 * 3600_000).toISOString(),
  },
  {
    slug: "kredyt-vs-gotowka",
    title: "Kupić na kredyt czy za gotówkę? Bankier.pl porównuje koszty",
    summary: "RRSO, prowizje i ubezpieczenia potrafią podbić cenę finansowania – kiedy kredyt ma sens?",
    content: "Przy wyborze kredytu liczy się pełne RRSO, prowizja i cross-sell. Jeśli masz poduszkę i brak alternatywnych inwestycji, kredyt może być droższy niż wypłata gotówki. Zawsze porównaj oferty w porównywarce, negocjuj marżę i unikaj zbędnych ubezpieczeń.",
    coverImage: "https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=1200&q=90",
    category: "finanse",
    tags: ["kredyt", "rrso", "porownywarka"],
    source: "Bankier.pl / oprac. FusionFinance",
    publishedAt: new Date(Date.now() - 27 * 3600_000).toISOString(),
  },
  {
    slug: "biznes-pln-umacnia",
    title: "Biznes: PLN mocny, eksporterzy zmieniają strategię cenową",
    summary: "Umocnienie złotego do EUR i USD wymusza renegocjacje cenników i zabezpieczenia kursowe.",
    content: "Silny PLN obniża przychody w złotych. Eksporterzy: aktualizacja cenników co kwartał, hedging forward na 3–6 miesięcy, dywersyfikacja walutowa faktur. Ważne: koszty surowców i transportu w USD mogą neutralizować część ryzyka.",
    coverImage: "https://images.unsplash.com/photo-1553729459-efe14ef6055d?w=1200&q=90",
    category: "biznes",
    tags: ["eksport", "pln", "hedging"],
    source: "FusionFinance.pl",
    publishedAt: new Date(Date.now() - 28 * 3600_000).toISOString(),
  },
  {
    slug: "pit-2025-ulgi",
    title: "PIT 2025: ulgi i odliczenia, o których łatwo zapomnieć",
    summary: "Ulga na internet, IKZE, darowizny, termomodernizacja – przypomnienie przed rozliczeniem.",
    content: "Przed złożeniem PIT-37/PIT-36 sprawdź: darowizny na OPP, ulgę na internet (do 760 zł), IKZE (odliczenie wpłat), termomodernizację (do 53 tys. zł), ulgę rehabilitacyjną, ulgę na dzieci. Korzystaj z e-PIT i miej dowody wpłat.",
    coverImage: "https://images.unsplash.com/photo-1450101499163-c8848c66ca85?w=1200&q=90",
    category: "finanse",
    tags: ["pit", "podatki", "ulgi"],
    source: "Money.pl / oprac. FusionFinance",
    publishedAt: new Date(Date.now() - 29 * 3600_000).toISOString(),
  },
  {
    slug: "notowania-gpw-otwarcie",
    title: "Notowania: WIG20 otwiera się wyżej, energia i banki prowadzą",
    summary: "Poranny przegląd sesji: które sektory ciągną indeksy i gdzie widać największe obroty.",
    content: "Na otwarciu WIG20 zyskuje dzięki energetyce i bankom, z lekkim obciążeniem ze strony górnictwa. Obroty skoncentrowane na PKO i PKN. W tle oczekiwania na dane CPI i decyzję EBC. Uwaga na wsparcia Fibo i poziomy L2.",
    coverImage: "https://images.unsplash.com/photo-1535320903710-d993d3d77d29?w=1200&q=90",
    category: "gielda",
    tags: ["wig20", "sesja", "obroty"],
    source: "Parkiet / oprac. FusionFinance",
    publishedAt: new Date(Date.now() - 30 * 3600_000).toISOString(),
  },
  {
    slug: "porownywarki-konta",
    title: "Porównywarka: konto osobiste 2025 – gdzie najniższe opłaty?",
    summary: "Ranking rachunków osobistych: opłaty za kartę, bankomaty, przelewy natychmiastowe.",
    content: "Przy wyborze ROR sprawdź: opłata za kartę i warunki zwolnienia (obrót, wpływ), darmowe wypłaty z bankomatów w PL/UE, przelewy natychmiastowe i BLIK, kantory online wbudowane. Dla oszczędności: konta z promocyjnym oprocentowaniem, ale z limitem kwoty.",
    coverImage: "https://images.unsplash.com/photo-1545239351-1141bd82e8a6?w=1200&q=90",
    category: "finanse",
    tags: ["konto", "bank", "porownywarka"],
    source: "FusionFinance.pl",
    publishedAt: new Date(Date.now() - 31 * 3600_000).toISOString(),
  },
];
